export const AIRPLANETYPE_SINGLE_REQUEST = "AIRPLANETYPE_SINGLE_REQUEST";
export const AIRPLANETYPE_SINGLE_SUCCESS = "AIRPLANETYPE_SINGLE_SUCCESS";
export const AIRPLANETYPE_SINGLE_FAIL = "AIRPLANETYPE_SINGLE_FAIL";